[workspace]
resolver = "2"

members = [
    "socks5",
    "client",
    "server",
    "examples",
]

[workspace.dependencies]
thiserror = "2.0.17"
async-dns = "0.1.1"
async-io = "2.6.0"
bytes = "1.10.1"
futures-lite = "2.6.1"
socks5 = { path = "socks5" }
tinyvec = "1.10.0"

