[package]
name = "socks5-server"
version = "0.5.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
async-dns.workspace = true
async-io.workspace = true
futures-lite.workspace = true
socks5.workspace = true
